language: node_js

node_js:
- '8'

sudo: required
services:
  - docker

before_install:
  - docker build -t client-service -f Dockerfile .

scripts:
  - docker run client-service npm run test -- --coverage