version: '3.6'

services:

  # PostgreSQL
  db:
    image: postgres:10.1-alpine
    hostname: db
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
  


  api:
    build: .
    command: npm start
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - NODE_ENV=$NODE_ENV
    depends_on:
      - db
