version: '3.6'

services:

  # PostgreSQLis 
  db:
    image: postgres:10.1-alpine
    hostname: db
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
      - 5432:5432
  


  api:
    build: .
    command: npm start
    volumes:
      - .:/app
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432/postgres
      - NODE_ENV=$NODE_ENV
    depends_on:
      - db
