version: '3.6'

services:

  # PostgreSQL, service need to be named postgres in order for Travis to work
  postgres:
    image: postgres:10.1-alpine
    hostname: db
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5433"
  


  api:
    build: .
    command: npm start
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5433/postgres
      - NODE_ENV=$NODE_ENV
    depends_on:
      - postgres
