version: '3.6'

services:

  # PostgreSQL, service need to be named postgres in order for Travis to work
  postgres:
    image: postgres:10.1-alpine
    hostname: db
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=clientsrv
    ports:
      - 5432:5432
  


  api:
    build: .
    command: npm start
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://admin:admin@postgres:5432/clientsrv
      - NODE_ENV=$NODE_ENV
    depends_on:
      - postgres
